site_name: Hyperactive
repo_url: https://github.com/SimonBlanke/Hyperactive
edit_uri: ""


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - toc:
      title: On this page

plugins:
  - glightbox
  - macros

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-square
  palette:
    primary: indigo
    accent: deep purple

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/blanke_simon
    - icon: fontawesome/brands/github 
      link: https://github.com/SimonBlanke/
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/simon-blanke/


nav:
  - Home:
    - Introduction: index.md

  - API Reference:
    - Basic Usage: api/basic_usage.md
    - Result Attributes: api/result_attributes.md
    - The objective function: api/objective_function.md
    - The search space: api/search_space.md
    - Optimizer classes: api/optimizer_classes.md

  - Optimization Algorithms:
    - Optimizers: optimizers.md
