site_name: Hyperactive
repo_url: https://github.com/SimonBlanke/Hyperactive
edit_uri: ""

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - toc:
      title: On this page

plugins:
  - glightbox
  - macros

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-square

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

  features:
    - navigation.indexes

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/blanke_simon
    - icon: fontawesome/brands/github
      link: https://github.com/SimonBlanke/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/simon-blanke/

nav:
  - Home:
      - Hyperactive: index.md

  - API Reference:
      - Basic Usage: api/basic_usage.md
      - Result Attributes: api/result_attributes.md

  - Tutorials:
      - The objective function: tutorials/objective_function.md
      - The search space: tutorials/search_space.md
      - Optimizer classes: tutorials/optimizer_classes.md

  - Optimization Algorithms:
      - optimizers/index.md
      - Hill Climbing: optimizers/hill_climbing.md
      - Stochastic Hill Climbing: optimizers/stochastic_hill_climbing.md
      - Simulated Annealing: optimizers/simulated_annealing.md
      - Repulsing Hill Climbing: optimizers/repulsing_hill_climbing.md
      - Downhill Simplex Optimization: optimizers/downhill_simplex.md
      - Pattern Search: optimizers/pattern_search.md
      - Powell's Method: optimizers/powells_method.md
      - Random Restart Hill Climbing: optimizers/random_restart_hill_climbing.md
      - Random Search: optimizers/random_search.md
      - Random Annealing: optimizers/random_annealing.md
      - Grid Search: optimizers/grid_search.md
      - Parallel Tempering: optimizers/parallel_tempering.md
      - Particle Swarm Optimization: optimizers/particle_swarm_optimization.md
      - Spiral Optimization: optimizers/spiral_optimization.md
      - Evolution Strategy: optimizers/evolution_strategy.md
      - Bayesian Optimization: optimizers/bayesian_optimization.md
      - Lipschitz Optimization: optimizers/lipschitz_optimization.md
      - DIRECT Algorithm: optimizers/direct_algorithm.md
      - Tree Structured Parzen Estimators: optimizers/tree_structured_parzen_estimators.md
      - Forest Optimization: optimizers/forest_optimization.md
