site_name: Hyperactive
repo_url: https://github.com/SimonBlanke/Hyperactive
edit_uri: ""

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs", "docs/code_examples"]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - toc:
      title: On this page

plugins:
  - glightbox
  - macros

theme:
  name: material
  icon:
    repo: fontawesome/brands/square-github

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

  features:
    - navigation.indexes

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/blanke_simon
    - icon: fontawesome/brands/github
      link: https://github.com/SimonBlanke/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/simon-blanke/

nav:
  - Home:
      - Hyperactive: index.md

  - Getting Started:
      - Quick Start Guide: tutorials/quickstart_v5.md
      - Migration Guide: tutorials/migration_guide.md

  - Base Classes:
      - api/index.md
      - Base Optimizer: api/base_optimizer.md
      - Base Experiment: api/base_experiment.md

  - Optimization Algorithms:
      - GFO Backend:
        - Hill Climbing: optimizers/gfo/hill_climbing.md
        - Stochastic Hill Climbing: optimizers/gfo/stochastic_hill_climbing.md
        - Repulsing Hill Climbing: optimizers/gfo/repulsing_hill_climbing.md
        - Random Restart Hill Climbing: optimizers/gfo/random_restart_hill_climbing.md
        - Simulated Annealing: optimizers/gfo/simulated_annealing.md
        - Downhill Simplex: optimizers/gfo/downhill_simplex.md
        - Random Search: optimizers/gfo/random_search.md
        - Grid Search: optimizers/gfo/grid_search.md
        - Powell's Method: optimizers/gfo/powells_method.md
        - Pattern Search: optimizers/gfo/pattern_search.md
        - Lipschitz Optimizer: optimizers/gfo/lipschitz_optimization.md
        - DIRECT Algorithm: optimizers/gfo/direct_algorithm.md
        - Parallel Tempering: optimizers/gfo/parallel_tempering.md
        - Particle Swarm Optimization: optimizers/gfo/particle_swarm_optimization.md
        - Spiral Optimization: optimizers/gfo/spiral_optimization.md
        - Genetic Algorithm: optimizers/gfo/genetic_algorithm/main_page.md
        - Evolution Strategy: optimizers/gfo/evolution_strategy.md
        - Differential Evolution: optimizers/gfo/differential_evolution/main_page.md
        - Bayesian Optimization: optimizers/gfo/bayesian_optimization.md
        - Tree Structured Parzen Estimators: optimizers/gfo/tree_structured_parzen_estimators.md
        - Forest Optimization: optimizers/gfo/forest_optimization.md
      - Optuna Backend:
        - TPE Optimizer: optimizers/optuna/tpe_optimizer.md
        - Random Optimizer: optimizers/optuna/random_optimizer.md
        - CMA-ES Optimizer: optimizers/optuna/cmaes_optimizer.md
        - GP Optimizer: optimizers/optuna/gp_optimizer.md
        - Grid Optimizer: optimizers/optuna/grid_optimizer.md
        - NSGA-II Optimizer: optimizers/optuna/nsga_ii_optimizer.md
        - NSGA-III Optimizer: optimizers/optuna/nsga_iii_optimizer.md
        - QMC Optimizer: optimizers/optuna/qmc_optimizer.md
      - Scikit-learn Backend:
        - Grid Search SK: optimizers/sklearn/grid_search_sk.md
        - Random Search SK: optimizers/sklearn/random_search_sk.md

  - Experiments:
      - Built-in Benchmarks:
        - Ackley Function: experiments/benchmarks/ackley.md
        - Sphere Function: experiments/benchmarks/sphere.md
        - Parabola Function: experiments/benchmarks/parabola.md
      - Integrations:
        - Scikit-learn CV: experiments/integrations/sklearn_cv.md
        - OptCV Interface: experiments/integrations/opt_cv.md
        - Sktime Forecasting: experiments/integrations/sktime_forecasting.md
      - Custom Experiments: experiments/custom_experiments.md

