site_name: Hyperactive
repo_url: https://github.com/SimonBlanke/Hyperactive
edit_uri: ""

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - glightbox
  - macros
      
theme:
  name: material
  icon:
    repo: fontawesome/brands/github-square
  palette:
    primary: indigo
    accent: deep purple

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

extra_css:
  - css/extra.css

extra:
  version:
    provider: mike

nav:
  - Introduction: index.md

  - Basic Usage: basic_usage.md
  - Optimizers: optimizers.md
